### ISSUE TITLE
Build failed on Arch Linux with termcap 1.3.1

### ISSUE THREAD

**Issue by NeoChen1024** [martinwguy/xvi#165]
Build failed on Arch Linux
Package version:
local/termcap 1.3.1-4
multilib/gcc-multilib 7.1.1-4 (multilib-devel)
core/binutils 2.28.0-4 (base-devel)
core/make 4.2.1-2 (base-devel)
core/automake 1.15.1-1 (base-devel)

Log: [Make Log](https://thunix.org/~neo_chen/TEMP/xvi.log)

**Comment by martinwguy** [comment]
THanks for reporting the build failure.

We had a similar with missing termcap variables on AIX, where one had to link with -lcurses
and placing some #ifdef AIX phrases in src/tcap_src.c

Missing tgoto is more worrying; I presume that other termcap calls like tgetent() are being found, which suggests to me a broken termcap library.

Do you know which termcap that is? GNU or BSD or an emulation over terminfo or something else?

Also, I see it's in local/ - does that mean it's been installed locally
and is a version different from the Arch repository? Or maybe that the library search path isn't looking in that directory (Sorry, I'm familiar enough with Arch linux to know these things)

Also, if you can find the libtermcap.a file, could you run
        nm libtermcap.a | grep " T "
and
        nm libtermcap.a | grep " C "
on it and send the output? With GNU libtermcap 1.3.1 I get:
000003dc T tgetent
000000fd T tgetflag
000000bd T tgetnum
00000133 T tgetstr
000002c5 T tputs
000000b1 T tgoto
00000075 T tparam
and
00000001 C PC
00000002 C ospeed
00000004 C tputs_baud_rate
00000004 C BC
00000004 C UP

Thanks again!

**Comment by NeoChen1024** [comment]
Because there's no termcap in Arch Linux Repository, I installed termcap from AUR.
It's using this implementation [http://www.catb.org/~esr/terminfo/](http://www.catb.org/~esr/terminfo/)

**Comment by NeoChen1024** [comment]
Actually there's no static library in Arch Linux, they are stripped by makepkg.
so I only have /usr/lib/libtermcap.so.1.3.1, which is a shared library.
And, there is no symbol in /usr/lib/libtermcap.so.1.3.1, I will try to compile it manually.

**Comment by NeoChen1024** [comment]
Thanks, after I modified the PKGBUILD to install static library, It works.

**Comment by martinwguy** [comment]
Thanks for checking that. If you have a working build recipe for Arch Linux I would be happy to add it to the repository.

Blessings

   M

**Comment by gdamjan** [comment]
there's ncurses5-compat-libs in AUR which should provide old APIs
