### ISSUE TITLE
Status/command line fails to resize with window size change

### ISSUE THREAD

**Issue by martinwguy** [martinwguy/xvi#27]
If you open xvi in an 80x25 window, then resize it to a wider size they type
:s/ffffffffffffffffffffffffffffff"
it stops visualizing the characters at 80 characters' width.

**Comment by martinwguy** [comment]
It's worse than I thought. If you open xvi in a 132x66 window, the :-command input line is still truncated at 80 characters

**Comment by jvvv** [comment]
See src/cmdmode.c lines 28 and 30. The size of the input buffer, inbuf[] is set by CMDSZ.

**Comment by martinwguy** [comment]
Well found! That explains the observed behaviour.
I was worried what it might do if the window is shorter than CMDSZ, but it does seem to handle that OK (by limiting the command's length to the width of the screen minus one.
vim and nvi just carry onto the next line, letting the screen scroll up by one.
For the moment I'll just up it to 132.

**Comment by martinwguy** [comment]
Well found!

vim, nvi and classic vi just wrap to the next line, which scrolls the whole screen by a line, then they redraw the whole screen when you hit enter (or ^C or Esc). Strangely, classic vi wraps at the 79th character, then subsequent lines at the 80th (or WIDTH-1 and WIDTH) while nvi and vim wrap both the first line and continuation lines at the 80th (or WIDTHth) character. I'm not sure how invasive a change that would be for xvi. It's not just a question of just carrying on printing characters and leaving he terminal to do its thing, as it also runs on character-memory-mapped displays, for example on the IBM PC in EGA and VGA modes it writes directly to the frame buffer, so we'd need to explicitly scroll the whole display ourselves to mimic this behaviour.

For the moment I'll just up the limit to alleviate the symptoms, but multi-line command input would be better.
