### ISSUE TITLE
LDFLAGS not included in final linker makefile rule

### ISSUE THREAD

**Issue by jvvv** [martinwguy/xvi#34]
For most of the unix makefiles, the LDFLAGS variable is at least declared, if not always defined, but mostly not included in the linker makefile rule.

I have a patch for this: https://github.com/jvvv/xvi/commit/6fe9df3c2fae744a7d01550b26f48211cb9ff338

I didn't want to hit you with a pull request for this until we had finished the remaining ^C handling, for which I have submitted #33 a few moments ago.

**Comment by martinwguy** [comment]
Good. Yes, I too found github's pull request thing awkward when there
are several independent changes in progress, making you having to wait
for one to be merged before beig able to submit the next. One way to
get round their inter-dependence is to make them on separate branches
and then launch pull requests from each branch, which is a little more
awkward but at least it doesn't block you while waiting for
review/merge.

However. Whatever. Today I'm online so if you want to make a regular
pull request for that go ahead.

**Comment by martinwguy** [comment]
Ah, I see you already did that! I even managed to import the change
into the master repo.

Cheers!

**Comment by martinwguy** [comment]
FIxed by 6fe9df3c
