### ISSUE TITLE
Resizing the window to make it longer gets status line refresh wrong

### ISSUE THREAD

**Issue by martinwguy** [martinwguy/xvi#47]
Lenghtening xvi's window under X, the status line remains where it was on-screen, and is not refreshed at the new last line until you do something (like press "o").  If the status line was, say on line 4, it remains on line 4 and is repainted on the window's last line.

**Comment by martinwguy** [comment]
Version b3ad1cd8 moves the status line as you resize as it should.

I tried a git bisect to find out which commit introduced the defect and it says
277fc303541d30ae942713064c65723593ce1252 is the first bad commit
Author: John Vogel <jvogel4@stny.rr.com>
Date:   Thu Dec 15 20:19:01 2016 -0500

    Simplify xvAdjustWindows for single window case.

so maybe you need to rework that. Before it, the status line popped into place after a <1sec delay.

**Comment by jvvv** [comment]
Yes, there were more commits in my private issue42 branch that I hadn't pushed, as well as much that I was still in progress of adding and related crashes that I was trying to track down. I should have informed you when I pushed those initial commits that there would be more to follow. Unfortunately, my hours at work increased and at the same time I got sick with a bad cold.

I have been working that private branch these last two days to try to isolate more memory corruptions related to #42. Would you prefer that I start a new branch for working this side of the resize bug(s) and reference this issue, #47? Or would you like to reopen #42?

I need to do some more testing on the memory corruption fixes and I also need to do some clean up before I push anything substantial. But I should have a basic fix for #47 pushed to the issue42 branch this evening. To be honest, it is only a cosmetic fix when compared to the memory corruption fixes I have been working.

I apologize for leaving this hanging and unfinished.

**Comment by martinwguy** [comment]
No worries. All I need to know is when I need to test and merge patches.
You've shown you know what you're doing, so all I need is some way to
see that the aberrant behaviour is gone or a new functionality is
working.

> Would you prefer that I
> start a new branch for working this side of the resize bug(s) and reference
> this issue, #47? Or would you like to reopen #42?

Whatever is easiest for you

> I need to do some more testing on the memory corruption fixes

What are the symptoms of the MC issues? I don't remember any

> I apologize for leaving this hanging and unfinished.

Absolutely no problem. Even if you take it up again next December xvi
is grateful to you! :)

Shall I commit the extended command line stuff you did? It's certainly
better than before, and maybe you have other things to look at than
the sexy scrolling thing I had envisioned...

    M

**Comment by jvvv** [comment]
Thanks for your patience.

I will reference this issue when preparing changes. That seems easier to me.

As far as memory corruption, I am reviewing my current changes to be sure that these are not the cause of the crashes I am seeing once resize issues start clearing up. This is the reason I am hesitant to push any of these changes yet.

I'd like to hold off on merging the command line stuff. I like your ideas and would like time to try to implement them. Also, I think there may need to be a little bit of polishing to the current new_commandline branch state before it should be pulled in.

**Comment by jvvv** [comment]
After reviewing all of my patches, I've managed to siphon out the changes that were causing crashes. I'm a bit embarrassed about them, so, less said, sooner mended.

**Comment by martinwguy** [comment]
Fixed by f99107ec
