### ISSUE TITLE
See if we can eliminate multiple "Interrupted" strings and logic by using imessage

### ISSUE THREAD

**Issue by martinwguy** [martinwguy/xvi#51]
xvi says show_message( "interrupted") in five places but there is a variable, "imessage" in events.c that does this in the main loop if (kdbintr).

See if the other calls can be reduced to setting that flag.

Roadmap:
- Write a test case for interrupting it in all the various places it happens (command mode, after first letter of a 2-letter command, in insert mode, replace mode, on the command line etc). That will serve to check whether setting imessage works in each of the cases.
- Try replacing each show_message() with setting imessage and see if it continues to test OK.

**Comment by martinwguy** [comment]
Similarly, it'd be nice to define who is responsible for setting/clearing kbdintr, and the difference between that being true and the command char being CTRL('C'). Both conditions seem to be tested all over the place.

What happens after "stty intr ^U" is also relevant. At present, if you do that, go into insert mode and say Ctrl-V Ctrl-U, you get a literal ^C inserted.

**Comment by jvvv** [comment]
There is a bit of a conundrum with the handling of the kbdintr flag and the imessage flag. At present, and even before I added the additional Ctrl-C handling, there is a case in the main event loop (for all ports except os2, I think) that checks if kbdintr is TRUE, sets the event type to Ev_breakin, then sets kbdintr to FALSE. I think that to get consistent SIGINT handling and specifically consistent SIGINT message handling, the kbdintr flag needs better handling.

Here's the catch with the way it's set up now: imessage isn't even looked at unless kbdintr is set, so we will be missing a good portion of the instances of SIGINT because kbdintr is unset when ever it is handled or converted to an event.

I think we need to change the kbdintr bool variable into an enum:

enum { kbd_PENDING, kbd_MESSAGE, kbd_CLEAR } kbdintr;

Then, we get rid of the Ev_breakin event, or at least don't use it for now. When kbd_PENDING is handled, kbdintr should be changed to kbd_MESSAGE. Then when we check kbdintr near the end of xvi_handle_event, we only print if kbdintr == kbd_MESSAGE.
Once we've printed the message for that instance, we set kbdintr to kbd_CLEAR. In this way we can handle SIGINT where ever we get it and it makes sense to, then only print the message near the end of the xvi_handle_event. Should be consistent, simple and easy to follow. I'll put theses ideas into code tonight and should be able to have it pushed to a branch tomorrow.

**Comment by jvvv** [comment]
#54 is the work I did last night and seems to cover this issue. Let me know if you find any problems or improvements you would like me to address.

**Comment by martinwguy** [comment]
On 01/01/2017, jvvv <notifications@github.com> wrote:
> There is a bit of a conundrum with the handling of the kbdintr flag and the
> imessage flag. At present, and even before I added the additional Ctrl-C
> handling, there is a case in the main event loop (for all ports except os2,
> I think) that checks if kbdintr is TRUE, sets the event type to Ev_breakin,
> then sets kbdintr to FALSE. I think that to get consistent SIGINT handling
> and specifically consistent SIGINT message handling, the kbdintr flag needs
> better handling.

Absolutely agree.

> imessage isn't even looked at unless kbdintr is set

Quite!

> enum { kbd_PENDING, kbd_MESSAGE, kbd_CLEAR } kbdintr;

OK, what I need is not a description of the mechanism of the solution;
it's something simpler that I can test without having to understand
the internals of that part as well as you do.  Descriptions of how the
solution work live in comments in the code, where a programmer's eyes
will fall when working on the same mechanisms or area of code in
future.

Yes, there do seem to be too many state variables with their fingers
in the keyboard interrupt! If you can understand (and comment) how it
should work, the solution should then be more obvious, and what it
means when the various variables have certain values should drop out
of this. Certainly having ckear in mind the latter is necessary; if we
don't know with certainty what a variable's values mean, there is no
hope of understanding, verifying, correcting its usage in the existing
code. If course, we also do a favour to future programmers who will
visit the same section of code in future...

It looks like several parallel alternative mechanisms for ^C have been
implemented, maybe while they were deciding how to do it, and what we
are left with is bits of all of them. You'd need to see whether a
BreakIn event can be made to do all that is needed or if that's
inadequate.
You seem to be moving towards a state machine to handle it, which is a
fine mechanism and pretty well understood. You'd need to say what it
means when the state variable is in each state, and what makes it move
from one state to another. When you have that, it should help make
clear how keyboard interrupts are to be processed and handled, which
code areas should be touching it and so on.

**Comment by jvvv** [comment]
Ok. So it seems I am running into troubles with my current changes to SIGINT and ^C handling. I think there are a couple of points that need to be addressed before a suitable solution can be worked out.

For one thing, since signals are asynchronous. When the kbdintr flag gets set in the SIGINT handler, we are turning the event into something that will be acted on synchronously. We can get multiple SIGINT's while still processing earlier ones.

One idea I was thinking about was to block/ignore SIGINT in the handler, then act on it inside the handler itself. This should work fine for unices and unix clones. As far as msdos/mswindows, I am not so sure. I tried looking at the signal stuff in the dos sources: msdoc_c.c, pc386.c, msdos_a.asm... but I don't have experience coding for dos/windows and have forgotten most of what I knew about those systems.

I have a branch I haven't pushed yet with a start on changes for asynchronous SIGINT handling, at least for the systems that follow posix signals.

**Comment by jvvv** [comment]
I have an initial implementataion of SIGINT handling without kbdintr and imessage flags at https://github.com/jvvv/xvi/tree/issue51a

**Comment by martinwguy** [comment]
That's an interesting solution. I've read through it.

I don't think that multiple interrupts are much of a problem, because
the kbd interrupt always returns us to normal mode, and an interrupt
in normal mode does nothing and stays in normal mode.

However, you will need to be very careful what you do in an
asynchronous routine, as it can be called in the middle of *any* other
code, even if it's in the middle of rewriting critical data structures
and hasn't yet left them in a sane state.
To be able to call from the interrupt handler any routine that changes
xvi's internal data, youì'll need to be sure that two things are
always true:
- that every other part of xvi that modifies that data does so in such
a way that, if unexpectedly paused at any point, everything is
guaranteed always to be in a sane state
- that if the internal data changes under some other routine's feet,
due to an interrupt happening, being handled asyncronously and
returning, every routine that uses that data is written in such a way
as to allow that.
I think these are unlikely to be true of xvi, which is probably why it
limits itself to setting a global variable and waiting until it gets
back to the event loop before doing anything about it, in a place
where it is sure that all the data-modifying routines have finished
doing their stuff.

The alternatives are to identify all data that can be used/modified by
the interrupt handler and to bracket every other use of those data in
the code with a "hold interrupts / re-enable interrupts" mechanism,
which promises to be rather a major change throughout all of the code,
with the risk of missing one case and leaving a bug that only crashes
when you press ^C at exactly the right moment - rare random crashes
almost impossible to repeat, hence nigh impossible to debug,

Unless there's something I'm missing here...

**Comment by jvvv** [comment]
On Sat, 07 Jan 2017 20:49:47 -0800
Martin Guy <notifications@github.com> wrote:

> That's an interesting solution. I've read through it.
> 
> I don't think that multiple interrupts are much of a problem, because
> the kbd interrupt always returns us to normal mode, and an interrupt
> in normal mode does nothing and stays in normal mode.
> 
> However, you will need to be very careful what you do in an
> asynchronous routine, as it can be called in the middle of *any* other
> code, even if it's in the middle of rewriting critical data structures
> and hasn't yet left them in a sane state.
> To be able to call from the interrupt handler any routine that changes
> xvi's internal data, youì'll need to be sure that two things are
> always true:
> - that every other part of xvi that modifies that data does so in such
> a way that, if unexpectedly paused at any point, everything is
> guaranteed always to be in a sane state
> - that if the internal data changes under some other routine's feet,
> due to an interrupt happening, being handled asyncronously and
> returning, every routine that uses that data is written in such a way
> as to allow that.
> I think these are unlikely to be true of xvi, which is probably why it
> limits itself to setting a global variable and waiting until it gets
> back to the event loop before doing anything about it, in a place
> where it is sure that all the data-modifying routines have finished
> doing their stuff.
> 
> The alternatives are to identify all data that can be used/modified by
> the interrupt handler and to bracket every other use of those data in
> the code with a "hold interrupts / re-enable interrupts" mechanism,
> which promises to be rather a major change throughout all of the code,
> with the risk of missing one case and leaving a bug that only crashes
> when you press ^C at exactly the right moment - rare random crashes
> almost impossible to repeat, hence nigh impossible to debug,
> 
> Unless there's something I'm missing here...
> 

Yeah, I'm not very proud of it, was just curious to see how bad it
would be to try it. I don't suggest we go that way. By doing it,
though, it's got me thinking about the kbdintr state in a different
light. I'm going to ponder and play around with this before pushing
anything right off. Thanks for looking at it. Hope you didn't
cringe too much as you read the changes.

**Comment by martinwguy** [comment]
Of the solutions we've seen so far, the interrupt event seems the
cleanest. If the irq were to set kdbintr and the event loop generate
an event from that, maybe you can just move the code you have here
from the interrupt routine itself to the event loop, where it will be
executed in a safe context, either with Ev_breakin (or whataver it's
called) or by checking kbdintr just before switch(event), leaving the
rest of the code just needing to check kdbintr where there are
potentially indefinite loops in the code.
Handling it as an event should also get rid of this bogus "interrupt
is CTRL-C" stuff, which is wrong when the interrupt character is not
^C. I think the only place you need to know what the interrupt
character is, is when they go ^V[interrupt] and need to insert the
character literally.

The issue here is that it's printing "Interrupted" all over the place,
sometimes putting the cursor back to its place on the screen, other
times not, maybe sometimes twice which is flaky.  What I'm really
looking for is to understand the irq handling, and simplifying it and
documenting it are steps towards having it work reliably in every
case.

**Comment by jvvv** [comment]
I've pushed [issue51b](https://github.com/jvvv/xvi/tree/issue51b). I think this is on the right track and perhaps should supercede #54.

**Comment by martinwguy** [comment]
It's looking good. If we can eliminate its CRTL-C fixation so much the better.

From the comment:
-       /*
-        * In some environments it's possible to type
-        * control-C without actually generating an interrupt,
-        * but if they do, in this context, they probably want
-        * the semantics of an interrupt anyway.
-        */
it seems there's a second case, other than ^V[Interrupt] in which we
need to know what the interrupt character is: in "some environments"
in which it can happen that it gets through without generating an
interrupt. Unfortunately it doesn't say in which environments - maybe
with original Unix's crufty signal handling mechanisms? Or maybe one
of the odd ones (Amiga, MSDOS etc).

To me, that suggests a variable kbd_intr_char or something similar,
that is the only thing to know which actual character is the keyboard
interrupt character for this session. In the original vi manual, ^C
has no special meaning and is described as "Unused".

**Comment by martinwguy** [comment]
Of course, that may be best handled as a separate issue from this
"Printing "Interrupted" everywhere" one.

**Comment by martinwguy** [comment]
Of course, that may be best handled as a separate issue from this
"Printing "Interrupted" everywhere" one.

**Comment by jvvv** [comment]
I'll work on trying to untie CTRL('C') from the kbdintr stuff.

As far as the comments, you are touching on exactly why I removed that bit. If there are systems out there that handle interrupts such that ^C is passed as a normal key sequence, then I think that for such systems it should be converted in the system specific code (ie, could convert ^C to kbdintr and/or Ev_breaking before calling xvi_handle_event). Just my 2 cents.

**Comment by martinwguy** [comment]
Yes... if we can find out which they are! For the moment I suggest we
commit these changes when you are happy with them, then make a new
issue for that.

**Comment by jvvv** [comment]
Ok, I will close my current PR for my issue51 branch and do a review of my issue51b branch before doing the PR for it. Thanks for your input.

**Comment by martinwguy** [comment]
Fixed by e869c4dc
