### ISSUE TITLE
The string/list member of params can cause invalid free in set_params.

### ISSUE THREAD

**Issue by jvvv** [martinwguy/xvi#57]
String and list type parameter in params variables never gets initialized. When a string or list type parameter is set in set_param, the current pointer is free'd if non-NULL. Because this structure member never gets initialized, it contains a garbage value. When set_param is called for a string or list type, it will try to free that garbage pointer.

**Comment by martinwguy** [comment]
If it is freeing garbage pointers, what's the symptom of this? Core dumps?

**Comment by martinwguy** [comment]
Or are they static data auto-initialised to 0?

**Comment by jvvv** [comment]
My mistake. I forgetting that because the params array is defined in the global scope, it has static duration and as such, all portions not explicitly initialized get implicitly initialized to zero or (as in this case) NULL.
