### ISSUE TITLE
Dynamic memory errors are generally not handled.

### ISSUE THREAD

**Issue by jvvv** [martinwguy/xvi#62]
This is one I've been seeing through out the code base. When malloc or brethren fail, a failure is often returned to the calling function but nothing seems to be done about the situation. I understand we don't want to just bail out without some kind of contingencies, but blindly continuing is not the way either.

**Comment by martinwguy** [comment]
Mmm. Ideally, when RAM runs out, it would be best if the user were
notified and it returned to normal mode so that the user could at
least try to save the file.

**Comment by jvvv** [comment]
Yes, that makes sense. But it seems to me that, at that point, any operation may fail if it needs to allocate space itself. I was thinking that perhaps some attempt could be made to free up some memory to facilitate an anticipated file save operation.

**Comment by martinwguy** [comment]
> I was thinking that perhaps
> some attempt could be made to free up some memory to facilitate an
> anticipated file save operation.

I thought that too, (like what, yank buffers? Undo history?) but it's
a fairly desperate measure. I'd say that if it runs out of RAM,
nothing is _guaranteed_ to work any more, but we can do our best to
make the experience as untraumatic as possible for the user, as long
as it doesn't involve upheavals in the code.

It may be that, to save the file, it doesn't need to call alloc(). If
it does, we could get trapped in a scenario where xvi says "Out of
memory", you try to save and it says "Out of memory" and so on, which
would be frustrating.

**Comment by martinwguy** [comment]
Incidentally, you can test this brutally by saying to bash:
   (ulimit -v 2500; src/xvi)

On this system (Debian 32-bit), the lowest value that still lets bash
start xvi is
   (ulimit -v 2452; src/xvi)
and a rough test
   :0r /etc/passwd
   yG p p p p p p p p
stops, says "Not enough memory!" and you can then save to a named file ":w foo"

I've checked the calls to alloc() from the file-saving path using gdb
breakpoints on alloc():
it is called three times, twice to save the ":w foo" line as last :
command and into the ^@ yank buffer, and once to create an argv[]
structure - all three have code to fail safely and proceed.

That just leaves any calls to alloc(), clr_alloc() and re_alloc()
where the return valus is not checked for NULL.

**Comment by jvvv** [comment]
I think we are of similar minds on this. It was something I was getting a little worried about because my command line changes rely on alloc/re_alloc. I think, though, that carefully recrafting my current code in alt_commnand branch can prevent calls to alloc/re_alloc in 'out-of-memory' situations. I can also start looking for unchecked *alloc calls to make sure we handle them well.

**Comment by martinwguy** [comment]
I've checked all calls to *alloc(* and they all fail safe.

**Comment by martinwguy** [comment]
However, most calls to flexaddch() are not checked.

**Comment by martinwguy** [comment]
And replchars() doesn't have a failure path, worsened by being called mostly from the ?_proc() functions that also don't have a way to indicate failure.
